name: build

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        ruby_version:
          - '3.0'
          - '2.7'
          - '2.6'
          - '2.5'
          # - 'jruby-9.2.17.0'
        gemfile:
          - gemfiles/rails_61.gemfile
          - gemfiles/rails_60.gemfile
          - gemfiles/rails_52.gemfile
          - gemfiles/rails_51.gemfile
          - gemfiles/rails_50.gemfile
          # - gemfiles/rails_edge.gemfile
        exclude:
          - ruby_version: '3.0'
            gemfile: gemfiles/rails_52.gemfile
          - ruby_version: '3.0'
            gemfile: gemfiles/rails_51.gemfile
          - ruby_version: '3.0'
            gemfile: gemfiles/rails_50.gemfile
          - ruby_version: '2.7'
            gemfile: gemfiles/rails_52.gemfile
          - ruby_version: '2.7'
            gemfile: gemfiles/rails_51.gemfile
          - ruby_version: '2.7'
            gemfile: gemfiles/rails_50.gemfile
          # - ruby_version: '2.6'
          #   gemfile: gemfiles/rails_edge.gemfile
          # - ruby_version: '2.5'
          #   gemfile: gemfiles/rails_edge.gemfile
    runs-on: ubuntu-18.04
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v2
      - name: Install curl
        run: sudo apt-get install curl libcurl4-openssl-dev
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - run: bundle exec rake
