name: Ruby

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
      - 'github-actions'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.5.8', '2.6.8', '2.7.4', '3.0.2', 'ruby-head' ] # 'jruby-9.2.11.1', 'jruby-head'
    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Install libcurl
      run: |
        sudo apt-get install libcurl4 libcurl3-gnutls libcurl4-openssl-dev -y

    - name: Build and test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 2
        rake
